#!/usr/bin/env bash

pgrep tmux >/dev/null || (
  tmux new -d -s delete-me
  tmux run-shell $HOME/.config/tmux/plugins/tmux-resurrect/scripts/restore.sh
  tmux kill-session -t delete-me
)

TmuxSelect

## EOF
