---

- name: Manage Ubuntu Users
  hosts: localhost
  become: true

  vars_files:
    - "{{ playbook_dir }}/../data/secrets.yaml.vault"

  tasks:
    - name: End the play on hosts that are not Linux
      ansible.builtin.meta: end_play
      when: not ansible_facts['system'] == "Linux"

    - name: Ensure user directories and groups exist
      ansible.builtin.group:
        name: "{{ item.username }}"
        gid: "{{ item.gid }}"
        state: present
      loop: "{{ users_data }}"

    - name: Create or update users
      ansible.builtin.user:
        name: "{{ item.username }}"
        uid: "{{ item.uid }}"
        group: "{{ item.username }}"
        password: "{{ item.password }}"
        state: present
        shell: /bin/bash
        groups: adm,sudo
        append: true
        # comment: "{{ item.metadata_1 }}"
      loop: "{{ users_data }}"

    - name: Conform PIN Password for GDM
      ansible.builtin.lineinfile:
        path: "/etc/custompinfile"
        mode: '0600'
        line: "{{ item.pin_password }}"
        create: true
        state: present
      loop: "{{ users_data }}"
      no_log: true
