---

- name: Manage Ubuntu Users
  hosts: localhost
  become: true

  vars_files:
    - secrets.yaml.vault

  tasks:
    - name: Ensure user directories and groups exist
      ansible.builtin.group:
        name: "{{ item.username }}"
        gid: "{{ item.gid }}"
        state: present
      loop: "{{ users_data }}"

    - name: Create or update users
      ansible.builtin.user:
        name: "{{ item.username }}"
        uid: "{{ item.uid }}"
        # gid: "{{ item.gid }}"
        password: "{{ item.password }}"
        state: present
        shell: /bin/bash
        # groups: adm sudo
        append: true
        # comment: "{{ item.metadata_1 }}"
      loop: "{{ users_data }}"
