---
- name: Apt Tasks
  hosts: localhost

  tasks:
    - name: Update cache and upgrade packages using generic package manager
      tags: privileged
      become: true
      ansible.builtin.package:
        upgrade: true
        update_cache: true
      when: not ansible_os_family == 'Darwin'

    - name: Install packages
      tags: privileged
      become: true
      ansible.builtin.package:
        name: "{{ packages }}"
      vars:
        ## Add Additional Packages Here
        packages:
          - vifm
          - glow
          - build-essential
          - libudev-dev
          - gnome-shell-extension-manager
          - gnome-tweaks
          - python3-pip
          - wl-clipboard
          - flatpak
          - autofs

      when: not ansible_os_family == 'Darwin'

