---
- name: Print all gathered facts
  hosts: localhost
  gather_facts: true
  tasks:
    # - name: Print all facts
    #   ansible.builtin.debug:
    #     # var: ansible_facts
    #     var: mount_facts

    - name: Mount Facts
      ansible.builtin.debug:
        msg: "{{ item.fstype }}"
      loop: "{{ ansible_facts.mounts }}"
