---
- name: Dump all facts to a JSON file
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Save facts to a file
      copy:
        content: "{{ hostvars[inventory_hostname] | to_nice_json }}"
        dest: "/tmp/{{ inventory_hostname }}_facts.json"
      delegate_to: localhost
