---
# This playbook checks for a user with a specific UID and GID, and
# renames the user if the username does not match the desired name.
- name: Ensure user with UID 1000 is named 'fargly'
  hosts: all
  become: yes # Use privilege escalation to run tasks as root

  vars:
    desired_user_name: 'fargly'
    user_id_to_check: 1000

  tasks:
    # Task 1: Check if a user with the specified UID exists.
    # The `getent` command queries the user database.
    # We register the output to a variable named `getent_user`.
    - name: Get user information for UID {{ user_id_to_check }}
      ansible.builtin.command: "getent passwd {{ user_id_to_check }}"
      register: getent_user
      failed_when: getent_user.rc not in [0, 2] # RC 0 is success, RC 2 means not found
      changed_when: false # This task doesn't change anything

    # Task 2: Check the username and conditionally rename it.
    # This task will only run if a user was found (rc == 0) and the
    # current username does not match our desired name.
    - name: Rename user to '{{ desired_user_name }}' if UID {{ user_id_to_check }} exists with a different name
      ansible.builtin.user:
        name: "{{ desired_user_name }}"
        uid: "{{ user_id_to_check }}"
        # Set gid to the same as uid, as is common for user accounts.
        # This will also ensure the group is created/updated if needed.
        group: "{{ user_id_to_check }}" 
        state: present
        append: yes # Ensure the user is not removed from other groups
      when: >
        getent_user.rc == 0 and
        (getent_user.stdout_lines[0].split(':')[0] != desired_user_name)

    # Optional Task 3: Inform the user if no change was needed.
    - name: User is already named '{{ desired_user_name }}'
      ansible.builtin.debug:
        msg: "User with UID {{ user_id_to_check }} is already named '{{ desired_user_name }}'. No changes were made."
      when: >
        getent_user.rc == 0 and
        (getent_user.stdout_lines[0].split(':')[0] == desired_user_name)

    # Optional Task 4: Inform the user if the UID was not found.
    - name: User with UID {{ user_id_to_check }} was not found
      ansible.builtin.debug:
        msg: "No user found with UID {{ user_id_to_check }}. No changes were made."
      when: getent_user.rc != 0

