## Playbook for Managaging Secrets (i.e., ssh keys, API keys, etc.)

- name: Extract SSH Private Key from Vault and Write to File
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - secrets.yaml.vault # This line tells Ansible to load variables from vault.yml

  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "~/.ssh"
        state: directory
        mode: '0700'

    - name: Write SSH private key to file
      ansible.builtin.copy:
        content: "{{ ssh_private_key }}"
        dest: "{{ ssh_private_key_name }}" # Change this to your desired filename
        mode: '0600' # Essential for private keys
      no_log: true # Prevent the key from appearing in logs

    - name: Set correct permissions for the key (redundant but good practice)
      ansible.builtin.file:
        path: "{{ ssh_private_key_name }}"
        mode: '0600'
      delegate_to: localhost



