---
- name: Adjust Peripherals
  hosts: localhost
  gather_facts: true

  vars:
    peripheral_acceleration_value: '0.40' # You can change this value
  tasks:
    - name: End if Host is not Ubuntu
      ansible.builtin.meta: end_play
      when: not ansible_distribution == "Ubuntu"

    - name: Ensure 'dconf' is installed
      tags: privileged
      ansible.builtin.package:
        name: dconf-cli
        state: present
      become: true

    - name: Ensure 'gnome-tweaks' is installed
      tags: privileged
      ansible.builtin.package:
        name: gnome-tweaks
        state: present
      become: true

    - name: Ensure 'gnome-shell-extension-manager' is installed
      tags: privileged
      ansible.builtin.package:
        name: gnome-shell-extension-manager
        state: present
      become: true

    - name: Install hidetopbar extension
      ansible.builtin.command:
        cmd: "uvx gnome-extensions-cli install hidetopbar@mathieu.bidon.ca"
      changed_when: false

    # - name: Install dash-to-dock extension
    #   ansible.builtin.command:
    #     cmd: "uvx gnome-extensions-cli install dash-to-dock@micxgx.gmail.com"
    #   changed_when: false

    - name: Ensure pip is installed
      tags: privileged
      ansible.builtin.package:
        name: python3-pip
        state: present
      become: true

    - name: Set touchpad acceleration
      ansible.builtin.command:
        cmd: "gsettings set org.gnome.desktop.peripherals.touchpad speed {{ peripheral_acceleration_value }}"
      changed_when: false

    - name: Set mouse acceleration
      ansible.builtin.command:
        cmd: "gsettings set org.gnome.desktop.peripherals.mouse speed {{ peripheral_acceleration_value }}"
      changed_when: false

    - name: Set natural-scroll to false for touchpad
      ansible.builtin.command: gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll false
      changed_when: false

    - name: Remap CapsLock as Ctrl Key
      ansible.builtin.command: gsettings set org.gnome.desktop.input-sources xkb-options "['caps:ctrl_modifier']"
      changed_when: false

    - name: Set idle screen timeout
      ansible.builtin.command: gsettings set org.gnome.desktop.session idle-delay 1800
      changed_when: false

    - name: Set idle timeout for Suspend Activate
      ansible.builtin.command: gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'suspend'
      changed_when: false

    - name: Set idle timeout for Suspend Set Timeout
      ansible.builtin.command: gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 7200
      changed_when: false

    - name: Register Terminal Profile
      ansible.builtin.command:
        cmd: "gsettings get org.gnome.Terminal.ProfilesList default"
      register: terminal_profile
      changed_when: false

    - name: Set Terminal Theme 1
      ansible.builtin.command: |
        gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile.stdout }}/ use-theme-colors false
      changed_when: false

    - name: Set Terminal Theme 2
      ansible.builtin.command: |
        gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile.stdout }}/  background-color 'rgb(23,20,33)'
      changed_when: false

    - name: Set Terminal Theme 3
      ansible.builtin.command: |
        gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile.stdout }}/   foreground-color 'rgb(208,207,204)'
      changed_when: false

    - name: Set Terminal Theme 4
      ansible.builtin.command: |
        gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile.stdout }}/   palette "['#000000000000', '#EEEE00000000', '#4E4E9A9A0606', '#C4C4A0A00000', '#34346565A4A4', '#757550507B7B', '#060698989A9A', '#D3D3D7D7CFCF', '#555557575353', '#EFEF29292929', '#8A8AE2E23434', '#FCFCE9E94F4F', '#72729F9FCFCF', '#ADADB7B72D2D', '#3434E2E2E2E2', '#FCFCFCECECEC']"
      changed_when: false

    - name: Set Terminal Theme 5
      ansible.builtin.command: |
        gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
      changed_when: false

    - name: Register Terminal Profile
      ansible.builtin.command:
        cmd: "gsettings list-recursively"
      register: tactile_gsettings
      changed_when: false

    - name: Check for a search match and set a boolean fact
      ansible.builtin.set_fact:
        is_tactile_enabled: "{{ (tactile_gsettings | select('search', 'tactile')) | length > 0 }}"

    - name: Set Tactile Gap
      ansible.builtin.command: gsettings set org.gnome.shell.extensions.tactile gap-size 8
      when: is_tactile_enabled
      changed_when: false

    - name: Set Overamplification On
      ansible.builtin.command: gsettings set org.gnome.desktop.sound allow-volume-above-100-percent true
      changed_when: false

    - name: Set Terminal Hotkey
      ansible.builtin.command: gsettings set org.gnome.settings-daemon.plugins.media-keys terminal "['<Alt>t']"
      changed_when: false

    - name: Set Window Maximumization Toggle
      ansible.builtin.command: gsettings set org.gnome.desktop.wm.keybindings toggle-maximized "['<Alt>z']"
      changed_when: false

    - name: Set Window Minimumization
      ansible.builtin.command: gsettings set org.gnome.desktop.wm.keybindings minimize "['<Alt>a']"
      changed_when: false

    - name: Set Dock to Auto-Hide 1
      ansible.builtin.command: gsettings set org.gnome.shell.extensions.dash-to-dock autohide true
      changed_when: false

    - name: Set Dock to Auto-Hide 2
      ansible.builtin.command: gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false
      changed_when: false

    - name: Set Dock to Page Position
      ansible.builtin.command: org.gnome.shell.extensions.dash-to-dock dock-position 'BOTTOM'
      changed_when: false

    - name: Set Background Image
      ansible.builtin.command: gsettings set org.gnome.desktop.background picture-uri-dark https://raw.githubusercontent.com/basecamp/omakub/master/themes/nord/background.png
      changed_when: false

    - name: Report Settings Gnome
      ansible.builtin.command:
        cmd: "gsettings list-recursively org.gnome.desktop.peripherals"
      register: peripheral_settings
      changed_when: false

    - name: Display peripheral settings
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ peripheral_settings.stdout_lines | select('search', 'touchpad speed|mouse speed|touchpad natural-scroll') | list }}"
      loop_control:
        label: "{{ item }}"

