---
- name: Adjust touchpad acceleration
  hosts: localhost
  become: yes  # Required to run commands as root if needed, but 'dconf' is often run as the user.
  vars:
    touchpad_acceleration_value: '0.40' # You can change this value
  tasks:
    - name: Ensure 'dconf' is installed
      ansible.builtin.package:
        name: dconf-cli
        state: present

    - name: Set touchpad acceleration
      ansible.builtin.command:
        cmd: "gsettings set org.gnome.desktop.peripherals.touchpad speed {{ touchpad_acceleration_value }}"
      become: no # Run the command as the user, not root, since 'dconf' settings are per-user.
      environment:
        # These are often needed for 'dconf' commands to work correctly
        XDG_CURRENT_DESKTOP: "GNOME"
        DBUS_SESSION_BUS_ADDRESS: "{{ lookup('env', 'DBUS_SESSION_BUS_ADDRESS') }}"
      register: set_speed_result

    - name: Display result of setting acceleration
      ansible.builtin.debug:
        msg: "Touchpad acceleration set to {{ touchpad_acceleration_value }}. Command output: {{ set_speed_result.stdout }}"

