---
- name: Disable automatic updates on Ubuntu servers
  hosts: localhost
  become: true
  gather_facts: yes

  tasks:
    - name: Ensure unattended-upgrades package is installed (though usually it is)
      ansible.builtin.apt:
        name: unattended-upgrades
        state: present
        update_cache: true
      when: ansible_os_family == "Debian" # Only run for Debian-based systems like Ubuntu

    - name: Disable automatic updates by commenting out relevant lines in 20auto-upgrades
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        # Use a regex to match the lines and ensure they are commented out
        regexp: '^(\s*(APT::Periodic::Update-Package-Lists|APT::Periodic::Unattended-Upgrade)\s*".*";)$'
        line: ' // \1' # Add '// ' to comment out the line
        backrefs: true
        state: present
      notify: Restart unattended-upgrades service
      # Ensure this task only runs if the file exists and is relevant to Ubuntu's update mechanism
      when: ansible_os_family == "Debian"

    - name: Create or update a custom configuration file to explicitly disable automatic updates
      ansible.builtin.copy:
        content: |
          APT::Periodic::Update-Package-Lists "0";
          APT::Periodic::Unattended-Upgrade "0";
        dest: /etc/apt/apt.conf.d/99disable-automatic-updates
        mode: '0644'
        owner: root
        group: root
      notify: Restart unattended-upgrades service
      when: ansible_os_family == "Debian"

    - name: Stop and disable the unattended-upgrades service
      ansible.builtin.systemd:
        name: unattended-upgrades
        state: stopped
        enabled: no
      ignore_errors: true
      when: ansible_os_family == "Debian"

  handlers:
    - name: Restart unattended-upgrades service
      ansible.builtin.systemd:
        name: unattended-upgrades
        state: restarted
      listen: "Restart unattended-upgrades service" # This handler will only be triggered by the notify keyword
      when: ansible_os_family == "Debian"

