---

- name: Import webi Playbook
  ansible.builtin.import_playbook: webi.yaml

# Main playbook: checks for file existence and conditionally runs a setup playbook.
- name: Conditional File Setup
  hosts: localhost
  gather_facts: true

  vars:
    utility_list:
      - ripgrep
      - fd
      - fzf
      - bat
      - bun
      - jq

  tasks:
    - name: Check for the existence of each file
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.local/bin/{{ item }}"
      loop: "{{ utility_list }}"
      register: utility_check_results

    - name: Run a "fix task" for non-existent files with webtask
      ansible.builtin.command: "{{ ansible_env.HOME }}/.local/bin/webi {{ item.item }}"
      loop: "{{ utility_check_results.results }}"
      changed_when: not item.stat.exists
